```{r}
library(PKPDmisc)
library(PKPDdatasets)
library(ggplot2)
```

@start step1
```{r }
ggplot(data = sd_oral_richpk, aes(x = Weight, group = Gender)) + 
  geom_histogram()  
```
@end step1


@start step2
```{r }
ggplot(data = sd_oral_richpk, aes(x = Weight, group = Gender)) + 
  geom_histogram(binwidth = 4, color = "black") + 
  labs(
    x="Weight (kg)", 
    y = "Count") + 
  theme_bw() + 
  base_theme()
```
@end step2


@start step3
```{r }
ggplot(data = sd_oral_richpk, aes(x = Weight, group = Gender)) + 
  geom_histogram(binwidth = 4, aes(color = Gender)) + 
  labs(
    x="Weight (kg)", 
    y = "Count") + 
  base_theme()
```
@end step3

@start step4
```{r }
ggplot(data = sd_oral_richpk, aes(x = Weight, group = factor(Gender))) + 
  geom_histogram(binwidth = 4, color = "black", aes(fill = Gender)) + 
  labs(
    x="Weight (kg)", 
    y = "Count") + 
  base_theme()
```
@end step4

@start step5
```{r }
ggplot(data = sd_oral_richpk, aes(x = Weight, group = factor(Gender))) + 
  geom_histogram(binwidth = 4, color = "black", aes(fill = Gender)) + 
  geom_vline(xintercept = 70, size = 1.5, color = "red") + 
  labs(
    x="Weight (kg)", 
    y = "Count") + 
  base_theme()
```
@end step5

Final result looks good!